### PR TITLE
magisk: fix OnePlus display issues, reorganize props

### LINKED ISSUE #92: 2.1.0 Breaks Fingerprint Sensor - OP8T
Installing the latest release of safetynet-fix "breaks" the fingerprint sensor on the OnePlus 8T. After installing the finger print sensor will say hardware unavailable. Removing the module and rebooting will make the sensor function again. At first I thought it was just a coincidence, however I did get confirmation of this behavior on the 8T on the telegram group as well.  Please let me know what other information I can supply that maybe helpful, it diagnosing this issue. I'll be happy to help.

### PR DESCRIPTION
**Pull request by osm0sis**
- vendor.boot.verifiedbootstate was a "late_prop" in MagiskHide so needs to be set at boot_completed; this works around OnePlus display mode and in-display fingerprint reader breakage when this prop is reset to green earlier in the boot
- tidy up prop groupings and document them a bit more

Fixes #92

### CODE REVIEW

File: riru/template/magisk_module/service.sh [hunk 1]
```diff
@@ -26,3 +27,13 @@ if [[ "$(cat /sys/fs/selinux/enforce)" == "0" ]]; then
     chmod 640 /sys/fs/selinux/enforce
     chmod 440 /sys/fs/selinux/policy
 fi
+
+# Late props which must be set after boot_completed
+{
+    until [[ "$(getprop sys.boot_completed)" == "1" ]]; do
```
Comment (kdrag0n) [inline riru/template/magisk_module/service.sh:33]: Is it really necessary to wait for this? I thought service.sh runs late enough that HALs and most system services won't be affected.

Comment (Didgeridoohan) [reply riru/template/magisk_module/service.sh:33]: It is necessary, or stuff breaks on OnePlus devices. See issue #92

Comment (osm0sis) [reply riru/template/magisk_module/service.sh:33]: It doesn't. I tried that first and it was still broken, unfortunately!

Comment (kdrag0n) [reply riru/template/magisk_module/service.sh:33]: Got it, thanks for confirming.

**Comment by kdrag0n** [comment]
Thanks!
