### PR TITLE
magisk: fix Oppo fingerprint reader issues

### LINKED ISSUE #157: Fingerprint
After installing the module the fingerprint sensor stops working on all Bank apps while I'm using a bypass that allows them to work

### PR DESCRIPTION
**Pull request by osm0sis**
- move ro.boot.vbmeta.device_state to late props since any earlier appears to break Oppo (ColorOS/OOS12+) fingerprint readers

Thanks @MlgmXyysd

Fixes #157

### CODE REVIEW

**Comment by osm0sis** [comment]
Awaiting verification that this is sufficient. ro.boot.verifiedbootstate might also be necessary.

**Comment by osm0sis** [comment]
Thanks @ToLive for confirming ro.boot.vbmeta.device_state was the one. 👍

**Comment by gossbill** [comment]
I tested this fix on my OnePlus 8T running Android 12 OOS Open Beta 1 and it fixed the fingerprint reader not working after installing Magisk.

**Comment by HuskyDG** [comment]
It's better to set all props after boot_completed to avoid weird issues on some devices/ROMs

**Comment by kdrag0n** [comment]
> It's better to set all props after boot_completed to avoid weird issues on some devices/ROMs

Can you elaborate on the issues you've noticed?

**Comment by osm0sis** [comment]
> It's better to set all props after boot_completed to avoid weird issues on some devices/ROMs

No, it's not. Earlier is better for something like root hiding, so we make specific exceptions only where necessary.

File: magisk/service.sh [hunk 1]
```diff
@@ -37,6 +37,9 @@ fi
     # avoid breaking Realme fingerprint scanners
     resetprop ro.boot.flash.locked 1
 
+    # avoid breaking Oppo fingerprint scanners
```
Comment (SebastianBar) [inline magisk/service.sh:40]: I suggest to update the comment, since it works for OnePlus as well (confirmed on OP7Pro A11, the same issue on banking apps gets resolved with this).

```suggestion
    # avoid breaking Oppo/OnePlus fingerprint scanners
```

Comment (osm0sis) [reply magisk/service.sh:40]: Nah, I intentionally put Oppo because OOS 12 is ColorOS.

**Comment by Stillhard** [comment]
Thx @osm0sis, i know this is OOT, just want to say hi to @MlgmXyysd - it's been a long time not seeing him in scenes

Great job to all of you as always

**Review by kdrag0n — APPROVED** [review]
Looks reasonable, thanks!x

**Comment by MlgmXyysd** [comment]
> Thx @osm0sis, i know this is OOT, just want to say hi to @MlgmXyysd - it's been a long time not seeing him in scenes
> 
> Great job to all of you as always

Say hello to all of you. I am currently busy with my studies and other projects.

File: magisk/service.sh (hunk 1 above)
Comment (MlgmXyysd) [reply magisk/service.sh:40]: > I suggest to update the comment, since it works for OnePlus as well (confirmed to work on OP7Pro A11 Stock ROM, the same issue on banking apps gets resolved with this).

And realme. The three of them can be collectively referred to as OPlus lmao.

**Comment by RubikPlay** [comment]
> [safenet-fix-v2.2.1_MOD.zip](https://github.com/kdrag0n/safetynet-fix/files/8774191/safetynet-fix-v2.2.1_MOD.zip) Приєднаний модуль, модифікований@osm0sis працює на OP8T з oxy12 і, ймовірно, на інших пристроях OnePlus і OPPO, які страждають від проблеми з датчиком відбитків пальців.
> 
> Повністю дякую@kdrag0nі@osm0sisробить це можливим.

This file not installed
